name: Build and Deploy React App to Azure Web App

on:
  push:
    branches:
      - master  # O la rama que estés usando para producción

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Usar la versión de Node.js que prefieras

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: FrontReact
        slot-name: production
        package: ./dist
